### ISSUE TITLE
Migrate benchmarks from zed to camelm2m

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/camel-m2m-gateway#4]

**Comment by hekonsek** [comment]
@ajurasz Will you handle this? Migration and possible merging of the benchmarks. I will highly appreciate that :) .

**Comment by ajurasz** [comment]
@hekonsek consider it done.

**Comment by ajurasz** [comment]
If you want to run benchmark in the way we did in <code>zed-camel-rpi-benchmark</code> you just need to set following property to false <code>paho.enabled</code>

and I didn't migrate <code>zed-boot-rpi-benchmark</code> as we decided this at some point.
