### ISSUE TITLE
Remove our benchmarks code on the behalf of the ManagedCamelContext and quickstarts

### ISSUE THREAD

**Issue by hekonsek** [hekonsek/camel-m2m-gateway#8]
@ajurasz I think that we can remove our benchmarks code [1]. Statistics are collected and exposed via ManagedCamelContext and JMX/Jolokia - we can use this. And instead of maintaining benchmarks code, we can just use quickstarts [2].

So If I would like to perform a benchmark I can just copy given quickstart [2] and read the statistics using the Camel JMX API [3] + Jolokia.

That would make a one piece of code less to maintain. What do you think?

[1] https://github.com/hekonsek/camel-m2m-gateway/tree/master/benchmarks
[2] https://github.com/hekonsek/camel-m2m-gateway/tree/master/quickstarts
[3] http://camel.apache.org/camel-jmx.html

**Comment by ajurasz** [comment]
Well I think that less code to maintain is always a good thing. And as discussed earlier this i a good idea with these quickstarts.

**Comment by hekonsek** [comment]
Done.
